FROM nginx:1.31.5-alpine3.24@sha256:72ba65eb42c10344912a84ff42408db7d34f2feb642204570ab8fc5ffd29f1d3

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/default.ssr.conf /etc/nginx/conf.d/default.conf

USER nginx

EXPOSE 8080 8443
