FROM node:20.20.1-alpine3.23@sha256:b88333c42c23fbd91596ebd7fd10de239cedab9617de04142dde7315e3bc0afa AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npm run build

FROM node:20.20.1-alpine3.23@sha256:b88333c42c23fbd91596ebd7fd10de239cedab9617de04142dde7315e3bc0afa AS runtime
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4000

COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev --ignore-scripts --legacy-peer-deps && npm cache clean --force

COPY --from=build --chown=node:node /app/dist/icy-angular ./dist/icy-angular

USER node
EXPOSE 4000

CMD ["node", "dist/icy-angular/server/server.mjs"]
