FROM nginx:1.31.5-alpine3.24@sha256:34f40471dea485273c5e2a04dd5e97a682332ceb4a9adecd67de450dcb2fb390

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/default.ssr.conf /etc/nginx/conf.d/default.conf

USER nginx

EXPOSE 8080 8443
