services:
  db:
    image: postgres:15
    container_name: iceforge_db
    restart: always
    environment:
      POSTGRES_USER: iceforge
      POSTGRES_PASSWORD: iceforgepassword
      POSTGRES_DB: iceforge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
      - external

  backend:
    build: ./app
    container_name: iceforge_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/iceforge_db
      SPRING_DATASOURCE_USERNAME: iceforge
      SPRING_DATASOURCE_PASSWORD: iceforgepassword
      IMAGE_BASE_URL: https://iceforge.fr/images/
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - backend_logs:/app/logs
      - icy_images_data:/app/uploads/images   # ✅ même volume partagé
    networks:
      - internal
      - external

  frontend:
    image: nginx:alpine
    container_name: iceforge_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - icy_images_data:/usr/share/nginx/html/images:ro

    networks:
      - external

  bot:
    build: ./bot
    container_name: iceforge_bot
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - backend
      - rabbitmq
    volumes:
      - bot_config:/app/config
    networks:
      - internal
      - external

  icy-images:
    image: nginx:latest
    container_name: icy-images
    volumes:
      - icy_images_data:/usr/share/nginx/html/images:ro   # ✅ même volume que backend
    ports:
      - "8081:80"
    networks:
      - internal
      - external

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iceforge_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: icy
      RABBITMQ_DEFAULT_PASS: icy123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
      - external

volumes:
  postgres_data:
    driver: local
  backend_logs:
    driver: local
  bot_config:
    driver: local
  icy_images_data:
    name: icy_images_data        # ✅ Nom fixe, inchangé, même dossier ou serveur
    driver: local

networks:
  internal:
    internal: true
  external:
    driver: bridge
