CREATE TABLE IF NOT EXISTS orbital_stations (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(140) NOT NULL UNIQUE,
    slug VARCHAR(160) NOT NULL UNIQUE,
    system_name VARCHAR(80) NOT NULL,
    station_kind VARCHAR(24) NOT NULL,
    orbit_kind VARCHAR(24) NOT NULL,
    orbit_target VARCHAR(140),
    lagrange_point VARCHAR(12),
    operator_name VARCHAR(140),
    wiki_url TEXT NOT NULL,
    image_url TEXT NOT NULL,
    game_version VARCHAR(20) NOT NULL DEFAULT '4.6',
    notes TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_station_kind CHECK (station_kind IN ('ORBITAL', 'LAGRANGE', 'OUTLAW', 'GATEWAY', 'SERVICE')),
    CONSTRAINT chk_orbit_kind CHECK (orbit_kind IN ('PLANET', 'MOON', 'LAGRANGE_POINT', 'ASTEROID_BELT', 'JUMP_POINT', 'UNKNOWN'))
);

CREATE INDEX IF NOT EXISTS idx_orbital_stations_system_sort
    ON orbital_stations (system_name, sort_order, name);

INSERT INTO orbital_stations (
    name, slug, system_name, station_kind, orbit_kind, orbit_target, lagrange_point, operator_name,
    wiki_url, image_url, game_version, notes, sort_order
)
VALUES
    ('Everus Harbor', 'everus-harbor', 'Stanton', 'ORBITAL', 'PLANET', 'Hurston', NULL, 'Hurston Dynamics',
     'https://starcitizen.tools/Everus_Harbor', 'https://media.starcitizen.tools/7/72/Hurston-everus-harbor-01.jpg', '4.6',
     'Station principale de Lorville.', 10),
    ('Baijini Point', 'baijini-point', 'Stanton', 'ORBITAL', 'PLANET', 'ArcCorp', NULL, 'ArcCorp',
     'https://starcitizen.tools/Baijini_Point', 'https://media.starcitizen.tools/6/6e/Arccorp-baijini-point-01.jpg', '4.6',
     'Station geostationnaire au-dessus d Area18.', 20),
    ('Seraphim Station', 'seraphim-station', 'Stanton', 'ORBITAL', 'PLANET', 'Crusader', NULL, NULL,
     'https://starcitizen.tools/Seraphim_Station', 'https://media.starcitizen.tools/9/9f/Seraphim_Station.png', '4.6',
     'Hub orbital de Crusader.', 30),
    ('Port Tressler', 'port-tressler', 'Stanton', 'ORBITAL', 'PLANET', 'microTech', NULL, NULL,
     'https://starcitizen.tools/Port_Tressler', 'https://media.starcitizen.tools/4/4a/Port-Tressler-Exterior-Alpha-3.12.png', '4.6',
     'Station orbitale de microTech.', 40),
    ('Grim HEX', 'grim-hex', 'Stanton', 'OUTLAW', 'ASTEROID_BELT', 'Yela', NULL, 'Nine Tails',
     'https://starcitizen.tools/Grim_HEX', 'https://media.starcitizen.tools/0/09/Star_Citizen_-_GrimHEX_close-up.png', '4.6',
     'Base outlaw dans la ceinture de Yela.', 50),

    ('HUR-L1 Green Glade Station', 'hur-l1-green-glade-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Hurston', 'L1', 'Rest & Relax',
     'https://starcitizen.tools/HUR-L1_Green_Glade_Station', 'https://media.starcitizen.tools/4/49/HUR-L1-Exterior-Alpha-3.12.png', '4.6',
     'Rest stop Hurston L1.', 110),
    ('HUR-L2 Faithful Dream Station', 'hur-l2-faithful-dream-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Hurston', 'L2', 'Rest & Relax',
     'https://starcitizen.tools/HUR-L2_Faithful_Dream_Station', 'https://media.starcitizen.tools/2/2c/HUR-L2-Exterior2-Alpha-3.12.png', '4.6',
     'Rest stop Hurston L2.', 111),
    ('HUR-L3 Thundering Express Station', 'hur-l3-thundering-express-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Hurston', 'L3', 'Rest & Relax',
     'https://starcitizen.tools/HUR-L3_Thundering_Express_Station', 'https://media.starcitizen.tools/a/a9/HUR-L3-Exterior-Alpha-3.12.png', '4.6',
     'Rest stop Hurston L3.', 112),
    ('HUR-L4 Melodic Fields Station', 'hur-l4-melodic-fields-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Hurston', 'L4', 'Rest & Relax',
     'https://starcitizen.tools/HUR-L4_Melodic_Fields_Station', 'https://media.starcitizen.tools/7/71/HUR-L4-Exterior-Alpha-3.12.png', '4.6',
     'Rest stop Hurston L4.', 113),
    ('HUR-L5 High Course Station', 'hur-l5-high-course-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Hurston', 'L5', 'Rest & Relax',
     'https://starcitizen.tools/HUR-L5_High_Course_Station', 'https://media.starcitizen.tools/7/7e/HUR-L5-Exterior-Alpha-3.12.png', '4.6',
     'Rest stop Hurston L5.', 114),

    ('CRU-L1 Ambitious Dream Station', 'cru-l1-ambitious-dream-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Crusader', 'L1', 'Rest & Relax',
     'https://starcitizen.tools/CRU-L1_Ambitious_Dream_Station', 'https://media.starcitizen.tools/e/e9/CRU-L1-Exterior-Alpha-3.12.png', '4.6',
     'Rest stop Crusader L1.', 120),
    ('CRU-L4 Shallow Fields Station', 'cru-l4-shallow-fields-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Crusader', 'L4', 'Rest & Relax',
     'https://starcitizen.tools/CRU-L4_Shallow_Fields_Station', 'https://media.starcitizen.tools/e/e1/CRU-L4-Exterior-Alpha-3.12.png', '4.6',
     'Rest stop Crusader L4.', 123),
    ('CRU-L5 Beautiful Glen Station', 'cru-l5-beautiful-glen-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'Crusader', 'L5', 'Rest & Relax',
     'https://starcitizen.tools/CRU-L5_Beautiful_Glen_Station', 'https://media.starcitizen.tools/4/4d/CRU-L5-Exterior-Alpha-3.14.jpg', '4.6',
     'Rest stop Crusader L5.', 124),

    ('ARC-L1 Wide Forest Station', 'arc-l1-wide-forest-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'ArcCorp', 'L1', 'Rest & Relax',
     'https://starcitizen.tools/ARC-L1_Wide_Forest_Station', 'https://media.starcitizen.tools/1/13/ARC-L1-Exterior-Alpha3.12.png', '4.6',
     'Rest stop ArcCorp L1.', 130),
    ('ARC-L2 Lively Pathway Station', 'arc-l2-lively-pathway-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'ArcCorp', 'L2', 'Rest & Relax',
     'https://starcitizen.tools/ARC-L2_Lively_Pathway_Station', 'https://media.starcitizen.tools/8/8b/ARC-L2-Exterior-Alpha-3.17.2.jpg', '4.6',
     'Rest stop ArcCorp L2.', 131),
    ('ARC-L3 Modern Express Station', 'arc-l3-modern-express-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'ArcCorp', 'L3', 'Rest & Relax',
     'https://starcitizen.tools/ARC-L3_Modern_Express_Station', 'https://media.starcitizen.tools/6/6c/ARC-L3-Exterior-Alpha-3.17.2.jpg', '4.6',
     'Rest stop ArcCorp L3.', 132),
    ('ARC-L4 Faint Glen Station', 'arc-l4-faint-glen-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'ArcCorp', 'L4', 'Rest & Relax',
     'https://starcitizen.tools/ARC-L4_Faint_Glen_Station', 'https://media.starcitizen.tools/3/3c/ARC-L4-Exterior-Alpha-3.17.2.jpg', '4.6',
     'Rest stop ArcCorp L4.', 133),
    ('ARC-L5 Yellow Core Station', 'arc-l5-yellow-core-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'ArcCorp', 'L5', 'Rest & Relax',
     'https://starcitizen.tools/ARC-L5_Yellow_Core_Station', 'https://media.starcitizen.tools/9/9b/ARC-L5-Exterior-Alpha-3.17.2.jpg', '4.6',
     'Rest stop ArcCorp L5.', 134),

    ('MIC-L1 Shallow Frontier Station', 'mic-l1-shallow-frontier-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'microTech', 'L1', 'Rest & Relax',
     'https://starcitizen.tools/MIC-L1_Shallow_Frontier_Station', 'https://media.starcitizen.tools/5/56/MIC-L1-Exterior1-Alpha-3.12.png', '4.6',
     'Rest stop microTech L1.', 140),
    ('MIC-L2 Long Forest Station', 'mic-l2-long-forest-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'microTech', 'L2', 'Rest & Relax',
     'https://starcitizen.tools/MIC-L2_Long_Forest_Station', 'https://media.starcitizen.tools/7/7e/MIC-L2-Exterior2-Alpha-3.17.2.jpg', '4.6',
     'Rest stop microTech L2.', 141),
    ('MIC-L3 Endless Odyssey Station', 'mic-l3-endless-odyssey-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'microTech', 'L3', 'Rest & Relax',
     'https://starcitizen.tools/MIC-L3_Endless_Odyssey_Station', 'https://media.starcitizen.tools/a/a6/MIC-L3-Exterior-Alpha-3.17.2.jpg', '4.6',
     'Rest stop microTech L3.', 142),
    ('MIC-L4 Red Crossroads Station', 'mic-l4-red-crossroads-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'microTech', 'L4', 'Rest & Relax',
     'https://starcitizen.tools/MIC-L4_Red_Crossroads_Station', 'https://media.starcitizen.tools/5/58/MIC-L4-Exterior2-Alpha-3.17.2.jpg', '4.6',
     'Rest stop microTech L4.', 143),
    ('MIC-L5 Modern Icarus Station', 'mic-l5-modern-icarus-station', 'Stanton', 'LAGRANGE', 'LAGRANGE_POINT', 'microTech', 'L5', 'Rest & Relax',
     'https://starcitizen.tools/MIC-L5_Modern_Icarus_Station', 'https://media.starcitizen.tools/b/b8/MIC-L5-Exterior1-Alpha-3.17.2.jpg', '4.6',
     'Rest stop microTech L5.', 144),

    ('Checkmate Station', 'checkmate-station', 'Pyro', 'LAGRANGE', 'LAGRANGE_POINT', 'Monox', 'L4', 'Rough & Ready',
     'https://starcitizen.tools/Checkmate_Station', 'https://media.starcitizen.tools/b/b8/Cutter_Approaching_Checkmate_Station.png', '4.6',
     'QG outlaw au point de Lagrange de Monox.', 210),
    ('Ruin Station', 'ruin-station', 'Pyro', 'OUTLAW', 'PLANET', 'Terminus', NULL, NULL,
     'https://starcitizen.tools/Ruin_Station', 'https://media.starcitizen.tools/0/0c/Ruin_Station%2C_Terminus%2C_Pyro.webp', '4.6',
     'Station emblématique de Terminus.', 220),
    ('Orbituary', 'orbituary', 'Pyro', 'OUTLAW', 'UNKNOWN', NULL, NULL, NULL,
     'https://starcitizen.tools/Orbituary', 'https://media.starcitizen.tools/2/24/Pyro_-_Orbituary_space_station.png', '4.6',
     'Station contestee en Pyro.', 230),
    ('Starlight Service Station', 'starlight-service-station', 'Pyro', 'SERVICE', 'UNKNOWN', NULL, NULL, NULL,
     'https://starcitizen.tools/Starlight_Service_Station', 'https://media.starcitizen.tools/4/4c/Starlight_Service_Station%2C_Pyro.webp', '4.6',
     'Station de services en Pyro.', 240),
    ('Stanton Gateway (Pyro)', 'stanton-gateway-pyro', 'Pyro', 'GATEWAY', 'JUMP_POINT', 'Stanton', NULL, NULL,
     'https://starcitizen.tools/Stanton_Gateway_(Pyro)', 'https://media.starcitizen.tools/0/06/Stanton_Gateway_and_jump_point%2C_Pyro_system.webp', '4.6',
     'Station porte de saut vers Stanton.', 250),
    ('Nyx Gateway (Pyro)', 'nyx-gateway-pyro', 'Pyro', 'GATEWAY', 'JUMP_POINT', 'Nyx', NULL, NULL,
     'https://starcitizen.tools/Nyx_Gateway_(Pyro)', 'https://media.starcitizen.tools/a/a9/Nyx_Gateway_Station_%28Pyro%29.png', '4.6',
     'Station porte de saut vers Nyx.', 251)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    system_name = EXCLUDED.system_name,
    station_kind = EXCLUDED.station_kind,
    orbit_kind = EXCLUDED.orbit_kind,
    orbit_target = EXCLUDED.orbit_target,
    lagrange_point = EXCLUDED.lagrange_point,
    operator_name = EXCLUDED.operator_name,
    wiki_url = EXCLUDED.wiki_url,
    image_url = EXCLUDED.image_url,
    game_version = EXCLUDED.game_version,
    notes = EXCLUDED.notes,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();
